[project]
name = "globcoasts"
version = "0.1.0"
description = ""
authors = [
    {name = "Your Name",email = "you@example.com"}
]
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "cmcrameri (>=1.9,<2.0)",
    "pyproj (>=3.7.1,<4.0.0)",
    "statsmodels (>=0.14.4,<0.15.0)",
    "cmocean (>=4.0.3,<5.0.0)",
    "geopandas (>=1.0.1,<2.0.0)",
    "cartopy (>=0.24.1,<0.25.0)",
    "h5py (>=3.13.0,<4.0.0)",
    "xarray (>=2025.1.2,<2026.0.0)",
    "global-land-mask (>=1.0.0,<2.0.0)",
    "netcdf4 (>=1.7.2,<2.0.0)",
    "tqdm (>=4.67.1,<5.0.0)",
    "scipy (>=1.15.2,<2.0.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
